name: pokedex
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.3+1
  get: ^4.6.6
  get_storage: ^2.1.1
  auto_size_text: ^3.0.0
  quickalert: ^1.1.0
  get_it: ^7.7.0
  logger: ^2.2.0
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/pokedex_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/pokedex_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/pokedex_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/pokedex_logo.png"

flutter:
  assets:
    - assets/gifs/
    - assets/images/
    - assets/logo/
  uses-material-design: true

