name: pokedex
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.3+1
  get: ^4.6.6
  get_storage: ^2.1.1
  auto_size_text: ^3.0.0
  quickalert: ^1.1.0
  get_it: ^7.7.0
  logger: ^2.2.0
  dropdown_search: ^5.0.6
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

